### ISSUE TITLE
Cannot Check Presence of validate Tag on Struct Method

### ISSUE THREAD

**Issue by shubham-cmyk** [go-simpler/musttag#116]
I am trying to enforce the presence of the validate tag on struct fields using golangci-lint with the musttag linter. However, despite correctly passing the function reference, the linter does not detect missing validate tags.

Steps To Reproduce : 

Config : 
```
linters-settings:
  musttag:
    functions:
      - name: github.com/go-playground/validator@v10.Validate.Struct
        tag: validate
        arg-pos: 1

linters:
  enable:
    - musttag
```

Code : 

```
type User struct {
    Name  string // Missing `validate` tag
    Email string `validate:"email"`
}
```
